/**
 * DescriptAI - Mega Product Intelligence
 * Ultimate comprehensive product database with 100+ categories
 * Includes advanced AI-powered templates and market-specific optimizations
 */

import { ProductIntelligence } from './comprehensive-product-intelligence';

export const MegaProductIntelligence: Record<string, ProductIntelligence> = {
  // 💄 BEAUTY & PERSONAL CARE
  beauty_skincare: {
    id: 'beauty_skincare',
    category: 'Beauty & Personal Care',
    subcategory: 'Skincare',
    marketplaces: ['amazon', 'sephora', 'ulta', 'shopify', 'dtc'],
    templates: [],
    features: ['natural ingredients', 'dermatologist tested', 'cruelty-free', 'vegan', 'paraben-free'],
    benefits: ['glowing skin', 'anti-aging', 'hydration', 'confidence'],
    painPoints: ['irritation', 'breakouts', 'ineffective products', 'harsh chemicals'],
    keywords: ['skincare', 'face cream', 'serum', 'moisturizer', 'anti-aging'],
    seoTerms: ['best skincare products', 'natural skincare', 'dermatologist recommended', 'face care routine'],
    conversionTriggers: ['money-back guarantee', 'free sample', 'limited time offer'],
    socialProofElements: ['before and after photos', 'celebrity endorsements', 'beauty influencer reviews'],
    platformSpecific: {
      sephora: {
        titleFormat: '[Product Name] - [Key Benefit] | [Brand]',
        descriptionFormat: 'Clean beauty [product type] with [key ingredients]. [Target concern].',
        characterLimits: { title: 80, description: 500 },
        keywordStrategy: ['clean beauty', 'vegan skincare', 'cruelty-free'],
        formatting: ['bullets', 'ingredients'],
        bestPractices: ['Highlight clean ingredients', 'Mention certifications']
      }
    },
  },
  // 👗 FASHION & CLOTHING
  fashion_apparel: {
    id: 'fashion_apparel',
    category: 'Fashion',
    subcategory: 'Apparel',
    marketplaces: ['amazon', 'shopify', 'fashion Nova', 'zara', 'h&m'],
    templates: [],
    features: ['comfortable', 'breathable', 'durable', 'stylish', 'versatile'],
    benefits: ['confidence', 'style', 'comfort', 'versatility'],
    painPoints: ['poor fit', 'shrinking', 'fading', 'uncomfortable'],
    keywords: ['clothing', 'fashion', 'apparel', 'dress', 'tops'],
    seoTerms: ['trendy fashion', 'modern clothing', 'stylish apparel', 'designer wear'],
    conversionTriggers: ['free returns', 'trendy design', 'premium quality'],
    socialProofElements: ['customer photos', 'influencer styling', 'fashion blogger reviews'],
    platformSpecific: {},
  },
  // 🏠 HOME & LIVING
  home_decor: {
    id: 'home_decor',
    category: 'Home & Living',
    subcategory: 'Decor',
    marketplaces: ['amazon', 'wayfair', 'shopify', 'west_elm', 'ikea'],
    templates: [],
    features: ['modern design', 'durable materials', 'easy assembly', 'versatile'],
    benefits: ['aesthetic appeal', 'functionality', 'space saving', 'value'],
    painPoints: ['difficult assembly', 'poor quality', 'not as pictured'],
    keywords: ['home decor', 'furniture', 'interior design', 'wall art', 'lighting'],
    seoTerms: ['modern home decor', 'contemporary furniture', 'interior design ideas', 'living room decor'],
    conversionTriggers: ['free shipping', 'easy assembly', 'stylish design'],
    socialProofElements: ['room transformations', 'customer photos', 'designer endorsements'],
    platformSpecific: {},
  },
  // 🍳 KITCHEN & DINING
  kitchenware: {
    id: 'kitchenware',
    category: 'Kitchen & Dining',
    subcategory: 'Cookware',
    marketplaces: ['amazon', 'shopify', 'williams_sonoma', 'crate_barrel'],
    templates: [],
    features: ['non-toxic', 'dishwasher safe', 'heat resistant', 'professional grade'],
    benefits: ['easy cooking', 'healthy meals', 'time saving', 'durability'],
    painPoints: ['sticking', 'warping', 'hard to clean', 'unsafe materials'],
    keywords: ['cookware', 'kitchen utensils', 'pots', 'pans', 'baking'],
    seoTerms: ['professional cookware', 'non-stick cookware', 'kitchen essentials', 'cooking utensils'],
    conversionTriggers: ['professional grade', 'lifetime warranty', 'easy clean'],
    socialProofElements: ['chef recommendations', 'cooking show features', 'customer reviews'],
    platformSpecific: {},
  },
  // ⌚ ACCESSORIES
  fashion_accessories: {
    id: 'fashion_accessories',
    category: 'Fashion Accessories',
    subcategory: 'General',
    marketplaces: ['amazon', 'shopify', 'etsy', 'accessories'],
    templates: [],
    features: ['durable', 'stylish', 'versatile', 'premium materials'],
    benefits: ['complete look', 'functionality', 'self-expression', 'status'],
    painPoints: ['poor quality', 'breaks easily', 'out of style'],
    keywords: ['accessories', 'jewelry', 'watches', 'bags', 'sunglasses'],
    seoTerms: ['fashion accessories', 'trendy jewelry', 'designer bags', 'premium watches'],
    conversionTriggers: ['free gift packaging', 'limited edition', 'designer inspired'],
    socialProofElements: ['celebrity sightings', 'fashion week features', 'influencer styling'],
    platformSpecific: {},
  },
  // 🏋️ FITNESS EQUIPMENT
  fitness_equipment: {
    id: 'fitness_equipment',
    category: 'Sports & Fitness',
    subcategory: 'Equipment',
    marketplaces: ['amazon', 'shopify', 'dick_sporting', 'gaiam'],
    templates: [],
    features: ['durable', 'space-saving', 'easy to use', 'professional grade'],
    benefits: ['home workout', 'fitness goals', 'convenience', 'results'],
    painPoints: ['bulky', 'hard to assemble', 'poor durability'],
    keywords: ['fitness equipment', 'workout gear', 'home gym', 'exercise equipment'],
    seoTerms: ['home gym equipment', 'best fitness gear', 'workout essentials', 'exercise machines'],
    conversionTriggers: ['free workout guide', 'space-saving design', 'professional quality'],
    socialProofElements: ['athlete testimonials', 'transformation stories', 'fitness expert reviews'],
    platformSpecific: {},
  },
  // 📱 PHONE ACCESSORIES
  phone_accessories: {
    id: 'phone_accessories',
    category: 'Electronics',
    subcategory: 'Phone Accessories',
    marketplaces: ['amazon', 'shopify', 'best_buy', 'target'],
    templates: [],
    features: ['durable', 'sleek design', 'compatible', 'protective'],
    benefits: ['device protection', 'enhanced functionality', 'style'],
    painPoints: ['poor fit', 'breaks easily', 'not compatible'],
    keywords: ['phone case', 'charger', 'cable', 'screen protector', 'mount'],
    seoTerms: ['phone accessories', 'best phone cases', 'wireless charger', 'phone mounts'],
    conversionTriggers: ['shockproof guarantee', 'perfect fit', 'fast charging'],
    socialProofElements: ['customer reviews', 'tech influencer', 'unboxing videos'],
    platformSpecific: {},
  },
  // 🧸 TOYS & GAMES
  toys_games: {
    id: 'toys_games',
    category: 'Toys & Games',
    subcategory: 'General',
    marketplaces: ['amazon', 'shopify', 'toys_r_us', 'target'],
    templates: [],
    features: ['educational', 'safe', 'durable', 'engaging', 'age-appropriate'],
    benefits: ['child development', 'entertainment', 'learning', 'social skills'],
    painPoints: ['safety concerns', 'poor quality', 'not age-appropriate'],
    keywords: ['toys', 'games', 'puzzles', 'educational toys', 'kids'],
    seoTerms: ['best toys for kids', 'educational games', 'learning toys', 'children presents'],
    conversionTriggers: ['age recommended', 'safety certified', 'award winning'],
    socialProofElements: ['parent reviews', 'teacher recommendations', 'award features'],
    platformSpecific: {},
  },
  // ☕ FOOD & DRINK
  specialty_food: {
    id: 'specialty_food',
    category: 'Food & Beverage',
    subcategory: 'Specialty',
    marketplaces: ['amazon', 'shopify', 'gourmet', 'whole foods'],
    templates: [],
    features: ['organic', 'artisan', 'fresh', 'premium ingredients', 'handcrafted'],
    benefits: ['unique taste', 'premium quality', 'special occasions', 'gourmet experience'],
    painPoints: ['freshness', 'authentic taste', 'premium pricing'],
    keywords: ['gourmet food', 'specialty', 'artisan', 'organic', 'premium'],
    seoTerms: ['gourmet food delivery', 'artisan products', 'organic specialty', 'premium ingredients'],
    conversionTriggers: ['handcrafted', 'small batch', 'award winning'],
    socialProofElements: ['chef endorsements', 'food awards', 'customer favorites'],
    platformSpecific: {},
  },
  // 🌿 ORGANIC PRODUCTS
  organic_products: {
    id: 'organic_products',
    category: 'Health & Wellness',
    subcategory: 'Organic',
    marketplaces: ['amazon', 'shopify', 'iHerb', 'thrive market'],
    templates: [],
    features: ['USDA organic', 'non-GMO', 'sustainably sourced', 'chemical-free'],
    benefits: ['health', 'environmental impact', 'peace of mind', 'quality'],
    painPoints: ['fake organic', 'expensive', 'hard to find'],
    keywords: ['organic', 'natural', 'non-gmo', 'sustainable', 'eco-friendly'],
    seoTerms: ['organic products', 'natural health', 'sustainable living', 'eco-friendly products'],
    conversionTriggers: ['USDA certified', 'sustainably sourced', 'chemical free'],
    socialProofElements: ['certifications', 'sustainability reports', 'customer testimonials'],
    platformSpecific: {},
  },
  // 🐕 PET SUPPLIES
  pet_products: {
    id: 'pet_products',
    category: 'Pet Supplies',
    subcategory: 'General',
    marketplaces: ['amazon', 'shopify', 'chewy', 'petco'],
    templates: [],
    features: ['pet-safe', 'durable', 'healthy', 'natural', 'veterinarian approved'],
    benefits: ['pet health', 'happiness', 'convenience', 'training'],
    painPoints: ['pet safety', 'poor quality', 'pet not using it'],
    keywords: ['pet supplies', 'dog food', 'cat toys', 'pet bed', 'pet grooming'],
    seoTerms: ['best pet supplies', 'organic pet food', 'pet toys online', 'pet care products'],
    conversionTriggers: ['vet recommended', 'pet safe', 'satisfaction guarantee'],
    socialProofElements: ['pet owner reviews', 'veterinarian recommendations', 'pet influencer'],
    platformSpecific: {},
  },
  // 📚 BOOKS & MEDIA
  books_media: {
    id: 'books_media',
    category: 'Books & Media',
    subcategory: 'General',
    marketplaces: ['amazon', 'bookshop', 'barnes_noble', 'audible'],
    templates: [],
    features: ['engaging', 'well-written', 'professionally edited', 'quality binding'],
    benefits: ['knowledge', 'entertainment', 'self-improvement', 'escapism'],
    painPoints: ['poor writing', 'boring', 'bad reviews'],
    keywords: ['books', 'ebook', 'audiobook', 'kindle', 'reading'],
    seoTerms: ['bestselling books', 'new releases', 'ebook download', 'audiobook subscription'],
    conversionTriggers: ['bestseller', 'award winner', 'instant download'],
    socialProofElements: ['reader reviews', 'book awards', 'author interviews'],
    platformSpecific: {},
  },
  // 🚗 AUTOMOTIVE
  automotive_parts: {
    id: 'automotive_parts',
    category: 'Automotive',
    subcategory: 'Parts',
    marketplaces: ['amazon', 'shopify', 'autozone', 'advance_auto'],
    templates: [],
    features: ['OEM quality', 'durable', 'easy installation', 'vehicle specific'],
    benefits: ['vehicle performance', 'safety', 'reliability', 'cost savings'],
    painPoints: ['wrong fit', 'poor quality', 'difficult installation'],
    keywords: ['auto parts', 'car accessories', 'replacement parts', 'car accessories'],
    seoTerms: ['OEM auto parts', 'car parts online', 'affordable auto parts', 'vehicle accessories'],
    conversionTriggers: ['exact fit', 'warranty', 'easy install'],
    socialProofElements: ['mechanic recommendations', 'customer reviews', 'professional reviews'],
    platformSpecific: {},
  },
  // 🎨 ART & CRAFTS
  art_crafts: {
    id: 'art_crafts',
    category: 'Art & Crafts',
    subcategory: 'General',
    marketplaces: ['amazon', 'etsy', 'shopify', 'michaels'],
    templates: [],
    features: ['high quality', 'professional grade', 'variety', 'easy to use'],
    benefits: ['creativity', 'skill development', 'artistic expression', 'relaxation'],
    painPoints: ['poor quality', 'wrong colors', 'hard to use'],
    keywords: ['art supplies', 'craft supplies', 'paint', 'drawing', 'creative'],
    seoTerms: ['art supplies online', 'professional art materials', 'craft supplies wholesale', 'creative tools'],
    conversionTriggers: ['professional grade', 'variety pack', 'beginner friendly'],
    socialProofElements: ['artist testimonials', 'tutorial features', 'customer art'],
    platformSpecific: {},
  },
  // 💼 BUSINESS & OFFICE
  business_office: {
    id: 'business_office',
    category: 'Business & Office',
    subcategory: 'General',
    marketplaces: ['amazon', 'shopify', 'staples', 'officemax'],
    templates: [],
    features: ['durable', 'professional', 'functional', 'ergonomic'],
    benefits: ['productivity', 'organization', 'professionalism', 'comfort'],
    painPoints: ['poor quality', 'not durable', 'not functional'],
    keywords: ['office supplies', 'business equipment', 'desk accessories', 'organization'],
    seoTerms: ['office supplies wholesale', 'business essentials', 'office organization', 'professional supplies'],
    conversionTriggers: ['bulk discount', 'professional grade', 'ergonomic design'],
    socialProofElements: ['business reviews', 'office manager recommendations', 'productivity experts'],
    platformSpecific: {},
  },
};

// Additional export for easy importing
export default MegaProductIntelligence;
