/**
 * DescriptAI - World Domination Categories
 * Final 10 categories to reach 50+ total
 * Categories: Pet, Garden, Automotive, Tools, Office, Music, Collectibles, Crafts, Party, Travel
 */

import { ProductIntelligence } from './comprehensive-product-intelligence';

export const WorldDominationCategories: Record<string, ProductIntelligence> = {
  // 🐾 PET SUPPLIES (High growth market)
  pet_supplies: {
    id: 'pet_supplies',
    category: 'Pet Supplies',
    subcategory: 'General',
    marketplaces: ['amazon', 'shopify', 'ebay', 'chewy'],
    templates: [],
    features: ['quality materials', 'safe for pets', 'durable'],
    benefits: ['happy pets', 'peace of mind', 'convenience'],
    painPoints: ['pet safety concerns', 'poor quality', 'expensive'],
    keywords: ['pet supplies', 'dog', 'cat', 'pet food', 'pet toys'],
    seoTerms: ['pet supplies', 'dog toys', 'cat food', 'pet accessories'],
    conversionTriggers: ['subscribe & save', 'free shipping'],
    socialProofElements: ['pet owner reviews', 'vet recommendations'],
    platformSpecific: {},
  },
  // 🌱 GARDEN & OUTDOOR
  garden: {
    id: 'garden',
    category: 'Garden & Outdoor',
    subcategory: 'General',
    marketplaces: ['amazon', 'shopify', 'ebay', 'homedepot'],
    templates: [],
    features: ['weather resistant', 'eco-friendly', 'easy to use'],
    benefits: ['beautiful garden', 'sustainability', 'relaxation'],
    painPoints: ['hard to maintain', 'poor quality', 'weather damage'],
    keywords: ['garden', 'outdoor', 'plants', 'landscaping', 'tools'],
    seoTerms: ['garden supplies', 'outdoor decor', 'landscaping tools'],
    conversionTriggers: ['seasonal deals', 'free shipping'],
    socialProofElements: ['gardener reviews', 'before/after photos'],
    platformSpecific: {},
  },
  // 🚗 AUTOMOTIVE
  automotive: {
    id: 'automotive',
    category: 'Automotive',
    subcategory: 'General',
    marketplaces: ['amazon', 'shopify', 'ebay', 'autozone'],
    templates: [],
    features: ['vehicle compatible', 'durable', 'easy installation'],
    benefits: ['vehicle performance', 'safety', 'style'],
    painPoints: ['compatibility issues', 'difficult installation', 'poor fit'],
    keywords: ['automotive', 'car accessories', 'auto parts', 'vehicle'],
    seoTerms: ['car accessories', 'auto parts', 'vehicle upgrades'],
    conversionTriggers: ['fitment guarantee', 'free returns'],
    socialProofElements: ['mechanic reviews', 'customer photos'],
    platformSpecific: {},
  },
  // 🔧 TOOLS & HARDWARE
  tools: {
    id: 'tools',
    category: 'Tools & Hardware',
    subcategory: 'General',
    marketplaces: ['amazon', 'shopify', 'ebay', 'homedepot'],
    templates: [],
    features: ['durable', 'ergonomic', 'professional quality'],
    benefits: ['get jobs done', 'save money', 'DIY satisfaction'],
    painPoints: ['poor quality', 'uncomfortable', 'breaks easily'],
    keywords: ['tools', 'hardware', 'DIY', 'power tools', 'hand tools'],
    seoTerms: ['power tools', 'hand tools', 'DIY tools', 'tool sets'],
    conversionTriggers: ['bundle deals', 'lifetime warranty'],
    socialProofElements: ['contractor reviews', 'DIY community'],
    platformSpecific: {},
  },
  // 📎 OFFICE SUPPLIES
  office: {
    id: 'office',
    category: 'Office Supplies',
    subcategory: 'General',
    marketplaces: ['amazon', 'shopify', 'ebay', 'staples'],
    templates: [],
    features: ['professional quality', 'ergonomic', 'efficient'],
    benefits: ['productivity', 'organization', 'professional image'],
    painPoints: ['disorganization', 'poor quality', 'uncomfortable'],
    keywords: ['office supplies', 'desk', 'organization', 'stationery'],
    seoTerms: ['office supplies', 'desk accessories', 'office organization'],
    conversionTriggers: ['bulk discounts', 'free shipping'],
    socialProofElements: ['business reviews', 'productivity experts'],
    platformSpecific: {},
  },
  // 🎵 MUSIC & INSTRUMENTS
  music: {
    id: 'music',
    category: 'Music & Instruments',
    subcategory: 'General',
    marketplaces: ['amazon', 'shopify', 'ebay', 'guitarcenter'],
    templates: [],
    features: ['quality sound', 'durable', 'professional grade'],
    benefits: ['creative expression', 'performance', 'enjoyment'],
    painPoints: ['poor sound quality', 'breaks easily', 'expensive'],
    keywords: ['music', 'instruments', 'guitar', 'piano', 'audio'],
    seoTerms: ['musical instruments', 'guitar', 'piano', 'music gear'],
    conversionTriggers: ['bundle deals', 'free lessons'],
    socialProofElements: ['musician reviews', 'artist endorsements'],
    platformSpecific: {},
  },
  // 🎨 COLLECTIBLES
  collectibles: {
    id: 'collectibles',
    category: 'Collectibles',
    subcategory: 'General',
    marketplaces: ['amazon', 'shopify', 'ebay', 'etsy'],
    templates: [],
    features: ['authentic', 'limited edition', 'quality materials'],
    benefits: ['investment', 'nostalgia', 'pride of ownership'],
    painPoints: ['counterfeits', 'overpriced', 'condition issues'],
    keywords: ['collectibles', 'rare', 'limited edition', 'vintage'],
    seoTerms: ['collectibles', 'rare items', 'limited edition', 'vintage'],
    conversionTriggers: ['authenticity certificate', 'limited stock'],
    socialProofElements: ['collector reviews', 'appraisal values'],
    platformSpecific: {},
  },
  // ✂️ CRAFTS & HOBBIES
  crafts: {
    id: 'crafts',
    category: 'Crafts & Hobbies',
    subcategory: 'General',
    marketplaces: ['amazon', 'shopify', 'ebay', 'etsy'],
    templates: [],
    features: ['quality materials', 'easy to use', 'versatile'],
    benefits: ['creativity', 'relaxation', 'personalized gifts'],
    painPoints: ['poor quality', 'difficult to use', 'limited options'],
    keywords: ['crafts', 'hobbies', 'DIY', 'art supplies', 'making'],
    seoTerms: ['craft supplies', 'hobby kits', 'DIY crafts', 'art materials'],
    conversionTriggers: ['project kits', 'tutorials included'],
    socialProofElements: ['crafter reviews', 'project photos'],
    platformSpecific: {},
  },
  // 🎉 PARTY SUPPLIES
  party: {
    id: 'party',
    category: 'Party Supplies',
    subcategory: 'General',
    marketplaces: ['amazon', 'shopify', 'ebay', 'etsy'],
    templates: [],
    features: ['themed designs', 'quality materials', 'complete sets'],
    benefits: ['memorable events', 'easy planning', 'impressive decor'],
    painPoints: ['poor quality', 'incomplete sets', 'generic designs'],
    keywords: ['party supplies', 'decorations', 'birthday', 'celebration'],
    seoTerms: ['party decorations', 'birthday supplies', 'event decor'],
    conversionTriggers: ['complete kits', 'bulk discounts'],
    socialProofElements: ['party photos', 'event planner reviews'],
    platformSpecific: {},
  },
  // ✈️ TRAVEL & LUGGAGE
  travel: {
    id: 'travel',
    category: 'Travel & Luggage',
    subcategory: 'General',
    marketplaces: ['amazon', 'shopify', 'ebay'],
    templates: [],
    features: ['durable', 'lightweight', 'TSA approved'],
    benefits: ['stress-free travel', 'organization', 'protection'],
    painPoints: ['heavy luggage', 'breaks easily', 'poor organization'],
    keywords: ['travel', 'luggage', 'suitcase', 'travel accessories', 'bag'],
    seoTerms: ['travel luggage', 'suitcases', 'travel accessories', 'bags'],
    conversionTriggers: ['warranty', 'free shipping'],
    socialProofElements: ['traveler reviews', 'travel blogger picks'],
    platformSpecific: {},
  },
};

