/**
 * DescriptAI - 20 Additional Product Categories
 * Expands from 9 → 29 categories
 * Electronics: +12 | Fashion: +5 | Home: +3
 */

import { ProductIntelligence } from './comprehensive-product-intelligence';

export const AdditionalCategories: Record<string, ProductIntelligence> = {
  // 📱 ELECTRONICS (12 new categories)
  tablets: {
    id: 'tablets',
    category: 'Electronics',
    subcategory: 'Tablets',
    marketplaces: ['amazon', 'shopify', 'ebay', 'bestbuy'],
    templates: [
      {
        tier: 'free',
        structure: 'portability + display + use_case',
        wordCount: 80,
        hooks: ['Your creative canvas', 'Power in your hands', 'Work and play anywhere'],
        bodyTemplate: '{productName} features {display} display and {processor}. Perfect for {useCase}. {battery} battery life.',
        cta: ['Get creative', 'Shop now'],
        emotionalTriggers: ['creativity', 'freedom'],
        powerWords: ['sleek', 'powerful', 'versatile', 'immersive'],
      },
    ],
    features: ['touchscreen', 'portable', 'long battery', 'fast processor'],
    benefits: ['work anywhere', 'entertainment on the go', 'creative freedom'],
    painPoints: ['heavy laptops', 'small phone screens', 'limited battery'],
    keywords: ['tablet', 'portable', 'display', 'touchscreen', 'ipad'],
    seoTerms: ['best tablet', 'tablet computer', 'portable device'],
    conversionTriggers: ['limited stock', 'free shipping', 'best seller'],
    socialProofElements: ['customer reviews', 'expert ratings', 'awards'],
    platformSpecific: {},
  },
  laptops: {
    id: 'laptops',
    category: 'Electronics',
    subcategory: 'Laptops',
    marketplaces: ['amazon', 'shopify', 'ebay', 'bestbuy'],
    templates: [],
    features: ['powerful processor', 'long battery', 'lightweight'],
    benefits: ['productivity', 'portability', 'performance'],
    painPoints: ['slow performance', 'heavy', 'poor battery'],
    keywords: ['laptop', 'notebook', 'computer', 'ultrabook'],
    seoTerms: ['best laptop', 'laptop deals', 'gaming laptop'],
    conversionTriggers: ['free shipping', 'extended warranty'],
    socialProofElements: ['reviews', 'ratings'],
    platformSpecific: {},
  },
  cameras: {
    id: 'cameras',
    category: 'Electronics',
    subcategory: 'Cameras',
    marketplaces: ['amazon', 'shopify', 'ebay', 'bestbuy'],
    templates: [],
    features: ['high resolution', 'fast autofocus', '4K video'],
    benefits: ['professional photos', 'memories', 'creative expression'],
    painPoints: ['blurry photos', 'slow shutter', 'low light issues'],
    keywords: ['camera', 'digital camera', 'mirrorless', 'DSLR'],
    seoTerms: ['best camera', 'professional camera', 'photography'],
    conversionTriggers: ['bundle deals', 'lens included'],
    socialProofElements: ['pro photographers', 'awards'],
    platformSpecific: {},
  },
  headphones: {
    id: 'headphones',
    category: 'Electronics',
    subcategory: 'Audio',
    marketplaces: ['amazon', 'shopify', 'ebay'],
    templates: [],
    features: ['noise cancelling', 'wireless', 'long battery'],
    benefits: ['immersive sound', 'focus', 'freedom'],
    painPoints: ['wired hassle', 'poor sound', 'uncomfortable'],
    keywords: ['headphones', 'earbuds', 'audio', 'wireless'],
    seoTerms: ['best headphones', 'noise cancelling', 'wireless earbuds'],
    conversionTriggers: ['free shipping', 'best seller'],
    socialProofElements: ['reviews', 'expert picks'],
    platformSpecific: {},
  },
  speakers: {
    id: 'speakers',
    category: 'Electronics',
    subcategory: 'Audio',
    marketplaces: ['amazon', 'shopify', 'ebay'],
    templates: [],
    features: ['powerful bass', 'wireless', 'waterproof'],
    benefits: ['great sound', 'party ready', 'portable'],
    painPoints: ['weak sound', 'wired', 'no portability'],
    keywords: ['speaker', 'bluetooth', 'audio', 'sound'],
    seoTerms: ['bluetooth speaker', 'portable speaker', 'wireless audio'],
    conversionTriggers: ['multi-buy deals', 'free shipping'],
    socialProofElements: ['reviews', 'ratings'],
    platformSpecific: {},
  },
  smartwatches: {
    id: 'smartwatches',
    category: 'Electronics',
    subcategory: 'Wearables',
    marketplaces: ['amazon', 'shopify', 'ebay', 'bestbuy'],
    templates: [],
    features: ['health tracking', 'notifications', 'GPS'],
    benefits: ['stay connected', 'fitness tracking', 'convenience'],
    painPoints: ['missed calls', 'no fitness data', 'bulky'],
    keywords: ['smartwatch', 'wearable', 'fitness tracker', 'watch'],
    seoTerms: ['best smartwatch', 'fitness watch', 'smart watch'],
    conversionTriggers: ['bundle deals', 'free bands'],
    socialProofElements: ['health experts', 'tech reviews'],
    platformSpecific: {},
  },
  gaming_consoles: {
    id: 'gaming_consoles',
    category: 'Electronics',
    subcategory: 'Gaming',
    marketplaces: ['amazon', 'shopify', 'ebay', 'bestbuy'],
    templates: [],
    features: ['4K gaming', 'fast load times', 'online multiplayer'],
    benefits: ['entertainment', 'social gaming', 'immersive experience'],
    painPoints: ['slow loading', 'limited games', 'poor graphics'],
    keywords: ['gaming console', 'playstation', 'xbox', 'nintendo'],
    seoTerms: ['best gaming console', 'video game system', 'next-gen gaming'],
    conversionTriggers: ['game bundle', 'limited edition'],
    socialProofElements: ['gamer reviews', 'awards'],
    platformSpecific: {},
  },
  monitors: {
    id: 'monitors',
    category: 'Electronics',
    subcategory: 'Displays',
    marketplaces: ['amazon', 'shopify', 'ebay', 'bestbuy'],
    templates: [],
    features: ['4K resolution', 'high refresh rate', 'HDR'],
    benefits: ['crystal clear', 'smooth gaming', 'productivity'],
    painPoints: ['low resolution', 'eye strain', 'small screen'],
    keywords: ['monitor', 'display', 'screen', '4K'],
    seoTerms: ['best monitor', 'gaming monitor', '4K display'],
    conversionTriggers: ['free shipping', 'extended warranty'],
    socialProofElements: ['reviews', 'tech awards'],
    platformSpecific: {},
  },
  keyboards: {
    id: 'keyboards',
    category: 'Electronics',
    subcategory: 'Peripherals',
    marketplaces: ['amazon', 'shopify', 'ebay'],
    templates: [],
    features: ['mechanical switches', 'RGB lighting', 'wireless'],
    benefits: ['comfortable typing', 'gaming performance', 'style'],
    painPoints: ['uncomfortable', 'slow response', 'wired'],
    keywords: ['keyboard', 'mechanical', 'gaming', 'wireless'],
    seoTerms: ['best keyboard', 'mechanical keyboard', 'gaming keyboard'],
    conversionTriggers: ['free shipping', 'RGB included'],
    socialProofElements: ['gamer reviews', 'tech awards'],
    platformSpecific: {},
  },
  mice: {
    id: 'mice',
    category: 'Electronics',
    subcategory: 'Peripherals',
    marketplaces: ['amazon', 'shopify', 'ebay'],
    templates: [],
    features: ['high DPI', 'ergonomic', 'wireless'],
    benefits: ['precise control', 'comfort', 'freedom'],
    painPoints: ['wrist pain', 'wired', 'inaccurate'],
    keywords: ['mouse', 'gaming mouse', 'wireless', 'ergonomic'],
    seoTerms: ['best mouse', 'gaming mouse', 'wireless mouse'],
    conversionTriggers: ['bundle deals', 'free pad'],
    socialProofElements: ['pro gamers', 'reviews'],
    platformSpecific: {},
  },
  routers: {
    id: 'routers',
    category: 'Electronics',
    subcategory: 'Networking',
    marketplaces: ['amazon', 'shopify', 'ebay', 'bestbuy'],
    templates: [],
    features: ['WiFi 6', 'mesh network', 'parental controls'],
    benefits: ['fast internet', 'whole-home coverage', 'security'],
    painPoints: ['dead zones', 'slow WiFi', 'dropped connections'],
    keywords: ['router', 'wifi', 'mesh', 'network'],
    seoTerms: ['best router', 'wifi router', 'mesh network'],
    conversionTriggers: ['free setup', 'extended warranty'],
    socialProofElements: ['tech reviews', 'ratings'],
    platformSpecific: {},
  },
  external_storage: {
    id: 'external_storage',
    category: 'Electronics',
    subcategory: 'Storage',
    marketplaces: ['amazon', 'shopify', 'ebay', 'bestbuy'],
    templates: [],
    features: ['large capacity', 'fast transfer', 'compact'],
    benefits: ['backup', 'portability', 'security'],
    painPoints: ['running out of space', 'slow transfers', 'data loss'],
    keywords: ['external drive', 'SSD', 'hard drive', 'storage'],
    seoTerms: ['external hard drive', 'SSD', 'portable storage'],
    conversionTriggers: ['free shipping', 'backup software'],
    socialProofElements: ['reviews', 'tech awards'],
    platformSpecific: {},
  },
  // 👗 FASHION (5 new categories)
  dresses: {
    id: 'dresses',
    category: 'Fashion',
    subcategory: 'Women\'s Clothing',
    marketplaces: ['amazon', 'shopify', 'ebay'],
    templates: [],
    features: ['flattering fit', 'quality fabric', 'versatile style'],
    benefits: ['confidence', 'comfort', 'style'],
    painPoints: ['poor fit', 'low quality', 'outdated style'],
    keywords: ['dress', 'women\'s fashion', 'clothing', 'style'],
    seoTerms: ['women\'s dress', 'fashion dress', 'evening dress'],
    conversionTriggers: ['free returns', 'size guide'],
    socialProofElements: ['customer photos', 'reviews'],
    platformSpecific: {},
  },
  suits: {
    id: 'suits',
    category: 'Fashion',
    subcategory: 'Men\'s Clothing',
    marketplaces: ['amazon', 'shopify', 'ebay'],
    templates: [],
    features: ['tailored fit', 'quality material', 'classic design'],
    benefits: ['professional look', 'confidence', 'style'],
    painPoints: ['poor fit', 'wrinkles', 'expensive'],
    keywords: ['suit', 'men\'s fashion', 'formal', 'business'],
    seoTerms: ['men\'s suit', 'business suit', 'formal wear'],
    conversionTriggers: ['free alterations', 'bundle deals'],
    socialProofElements: ['customer reviews', 'style guides'],
    platformSpecific: {},
  },
  activewear: {
    id: 'activewear',
    category: 'Fashion',
    subcategory: 'Sports Apparel',
    marketplaces: ['amazon', 'shopify', 'ebay'],
    templates: [],
    features: ['moisture-wicking', 'stretchy', 'breathable'],
    benefits: ['comfort', 'performance', 'style'],
    painPoints: ['sweaty', 'uncomfortable', 'restrictive'],
    keywords: ['activewear', 'gym clothes', 'workout', 'fitness'],
    seoTerms: ['athletic wear', 'gym clothes', 'workout gear'],
    conversionTriggers: ['multi-buy deals', 'free shipping'],
    socialProofElements: ['athlete endorsements', 'reviews'],
    platformSpecific: {},
  },
  footwear: {
    id: 'footwear',
    category: 'Fashion',
    subcategory: 'Shoes',
    marketplaces: ['amazon', 'shopify', 'ebay'],
    templates: [],
    features: ['comfortable', 'durable', 'stylish'],
    benefits: ['all-day comfort', 'style', 'support'],
    painPoints: ['uncomfortable', 'wears out', 'blisters'],
    keywords: ['shoes', 'footwear', 'sneakers', 'boots'],
    seoTerms: ['best shoes', 'footwear', 'sneakers', 'boots'],
    conversionTriggers: ['free shipping', 'easy returns'],
    socialProofElements: ['reviews', 'style guides'],
    platformSpecific: {},
  },
  accessories: {
    id: 'accessories',
    category: 'Fashion',
    subcategory: 'Accessories',
    marketplaces: ['amazon', 'shopify', 'ebay'],
    templates: [],
    features: ['quality materials', 'versatile', 'stylish'],
    benefits: ['complete outfit', 'style', 'functionality'],
    painPoints: ['cheap quality', 'outdated', 'limited options'],
    keywords: ['accessories', 'bags', 'belts', 'scarves'],
    seoTerms: ['fashion accessories', 'bags', 'belts', 'scarves'],
    conversionTriggers: ['bundle deals', 'gift wrapping'],
    socialProofElements: ['style influencers', 'reviews'],
    platformSpecific: {},
  },
  // 🏠 HOME (3 new categories)
  furniture: {
    id: 'furniture',
    category: 'Home',
    subcategory: 'Furniture',
    marketplaces: ['amazon', 'shopify', 'ebay', 'wayfair'],
    templates: [],
    features: ['durable', 'comfortable', 'stylish design'],
    benefits: ['comfort', 'style', 'functionality'],
    painPoints: ['uncomfortable', 'poor quality', 'hard to assemble'],
    keywords: ['furniture', 'home decor', 'living room', 'bedroom'],
    seoTerms: ['home furniture', 'living room furniture', 'bedroom furniture'],
    conversionTriggers: ['free shipping', 'assembly included'],
    socialProofElements: ['customer photos', 'reviews'],
    platformSpecific: {},
  },
  kitchen_appliances: {
    id: 'kitchen_appliances',
    category: 'Home',
    subcategory: 'Kitchen',
    marketplaces: ['amazon', 'shopify', 'ebay', 'bestbuy'],
    templates: [],
    features: ['efficient', 'easy to clean', 'modern design'],
    benefits: ['time-saving', 'convenience', 'better cooking'],
    painPoints: ['time-consuming', 'hard to clean', 'unreliable'],
    keywords: ['kitchen appliance', 'cooking', 'blender', 'mixer'],
    seoTerms: ['kitchen appliances', 'cooking appliances', 'small appliances'],
    conversionTriggers: ['free shipping', 'recipe book included'],
    socialProofElements: ['chef endorsements', 'reviews'],
    platformSpecific: {},
  },
  bedding: {
    id: 'bedding',
    category: 'Home',
    subcategory: 'Bedroom',
    marketplaces: ['amazon', 'shopify', 'ebay'],
    templates: [],
    features: ['soft material', 'breathable', 'durable'],
    benefits: ['better sleep', 'comfort', 'style'],
    painPoints: ['rough fabric', 'wrinkles', 'fades'],
    keywords: ['bedding', 'sheets', 'comforter', 'pillows'],
    seoTerms: ['bedding sets', 'sheets', 'comforters', 'pillows'],
    conversionTriggers: ['bundle deals', 'free shipping'],
    socialProofElements: ['reviews', 'sleep experts'],
    platformSpecific: {},
  },
};

